image: debian/testing
packages:
  - libcurl4-openssl-dev
  - libelf-dev
  - libdw-dev
  - libsqlcipher-dev
  - libsqlcipher0
  - cmake
  - curl
  - gcc
  - binutils-dev
  - libiberty-dev
sources:
  - https://git.sr.ht/~gbmor/rtcoin
environment:
  PATH: "$HOME/.cargo/bin:/bin:/usr/bin:$PATH"
tasks:
  - setup: |-
      curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
      source $HOME/.cargo/env
  - build: |-
      cd $HOME/rtcoin
      $HOME/.cargo/bin/cargo test
      $HOME/.cargo/bin/cargo build