language: rust

rust:
  - stable
  - beta
  - nightly

os: 
  - linux

dist: xenial

env:
  global:
    - CARGO_MAKE_RUN_CODECOV="true"

script: 
  - cargo install --debug cargo-make
  - cargo make ci-flow
