[package]
name = "rtcoin-client"
version = "0.1.0"
authors = ["Ben Morrison <ben@gbmor.dev>"]
edition = "2018"

[dependencies]
#bcrypt = "0.5"
chrono = "0.4"
#simplelog = "0.6"
clap = "2.33"
rtcoin-server = { path = "../rtcoin-server" }
