[package]
name = "rtcoin"
version = "0.1.0"
authors = ["Ben Morrison <ben@gbmor.dev>"]
edition = "2018"

[dependencies]
librtcoin-client = { path = "../librtcoin-client" }
librtcoin-daemon = { path = "../librtcoin-daemon" }
clap = "2.33"
