[package]
name = "rtcoin-server"
version = "0.1.0"
authors = ["Ben Morrison <ben@gbmor.dev>"]
edition = "2018"

[dependencies]
aes-soft = "0.3"
#bcrypt = "0.5"
block-modes = "0.3"
chrono = "0.4"
hex-literal = "0.1"
hmac = "0.7"
#simplelog = "0.6"
ryu = "1.0"
sha2 = "0.8"
sqlite = "0.25"
